services:
  node:
    image: canopynetwork/canopy:latest
    container_name: node
    restart: unless-stopped
    command: ["start"]
    ports:
      - "9001:9001" # TCP P2P
    expose:
      - "50000" # Wallet
      - "50001" # Explorer
      - "50002" # RPC
      - "50003" # Admin RPC
    volumes:
      - ./data:/root/.canopy
      - ./config/genesis.json:/root/.canopy/genesis.json
      - ./config/config.json:/root/.canopy/config.json
    secrets:
      - source: validator_key
        target: /root/.canopy/validator_key.json
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: "2.0"

secrets:
  validator_key:
    file: ./config/validator_key.json
