services:
  node:
    image: canopynetwork/canopy:latest
    container_name: node
    restart: unless-stopped
    command: ["start"]
    ports:
      - "9001:9001" # TCP P2P
      - "50000:50000" # Wallet
      - "50001:50001" # Explorer
      - "50002:50002" # RPC
      - "50003:50003" # Admin RPC
    volumes:
      - ./data:/root/.canopy
      - ./config/genesis.json:/root/.canopy/genesis.json:ro
      - ./config/config.json:/root/.canopy/config.json:ro
      - ./config/keystore.json:/root/.canopy/keystore.json
    secrets:
      - source: validator_key
        target: /root/.canopy/validator_key.json
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: "2.0"

  # use it to generate a new validator key:
  # docker compose run --rm --no-deps -it keygen
  keygen:
    image: canopynetwork/canopy-test:cli
    profiles: ["init"]
    volumes:
      - ./config:/app/config
    command: ["new-validator-key", "--data-dir", "./config"]

secrets:
  validator_key:
    file: ./config/validator_key.json
